### ISSUE TITLE
CSS bug after clicking event link

### ISSUE THREAD

**Issue by schneidmaster** [clerb/clerb-rails#3]
If you click one of the "View on Meetup" links, it opens the Meetup URL in a new tab -- but if you then close the tab and return to our site, the link text appears to be missing:

<img width="268" alt="screenshot 2018-09-18 12 49 58" src="https://user-images.githubusercontent.com/1896112/45703166-8432f300-bb41-11e8-9a78-6a67f138bcc0.png">

The text itself is still there, but it looks like our bootstrap theme has a CSS `:focused` class selector which is making the text green. This seems undesirable at least for our site -- we should just override it back to white.

**Comment by eacallam** [comment]
I'll work on this with Vicki!
